ALTER TABLE "race_card" DROP CONSTRAINT IF EXISTS "race_card_fk0";

ALTER TABLE "race_card" DROP CONSTRAINT IF EXISTS "race_card_fk1";

ALTER TABLE "command" DROP CONSTRAINT IF EXISTS "command_fk0";

ALTER TABLE "race_detail" DROP CONSTRAINT IF EXISTS "race_detail_fk0";

ALTER TABLE "race_detail" DROP CONSTRAINT IF EXISTS "race_detail_fk1";

ALTER TABLE "event" DROP CONSTRAINT IF EXISTS "event_fk0";

ALTER TABLE "event" DROP CONSTRAINT IF EXISTS "event_fk1";

ALTER TABLE "bet" DROP CONSTRAINT IF EXISTS "bet_fk0";

ALTER TABLE "bet" DROP CONSTRAINT IF EXISTS "bet_fk1";

ALTER TABLE "account" DROP CONSTRAINT IF EXISTS "account_fk0";

ALTER TABLE "account" DROP CONSTRAINT IF EXISTS "account_fk1";

DROP TABLE IF EXISTS "race_card";

DROP TABLE IF EXISTS "horse";

DROP TABLE IF EXISTS "command";

DROP TABLE IF EXISTS "race_detail";

DROP TABLE IF EXISTS "event";

DROP TABLE IF EXISTS "bet";

DROP TABLE IF EXISTS "user";

DROP TABLE IF EXISTS "account";

DROP TABLE IF EXISTS "security_level";

DROP TABLE IF EXISTS "racecourse";

