INSERT INTO "user" (first_name, last_name,gender,date,address) VALUES ('Fedor','Gvin','m','10.12.2016','les');
INSERT INTO "user" (first_name, last_name,gender,date,address) VALUES ('Mihal','Uro','m','11.02.2015','hom');
INSERT INTO "user" (first_name, last_name,gender,date,address) VALUES ('Olga','Ehova','f','01.05.2014','saray');
INSERT INTO "user" (first_name, last_name,gender,date,address) VALUES ('Бобик','Шариков','m','12.03.2012','будка');
INSERT INTO "user" (first_name, last_name,gender,date,address) VALUES ('Female','Masha','f','11.02.2015','usa');
INSERT INTO "user" (first_name, last_name,gender,date,address) VALUES ('Male','Her','m','02.05.2011','ger');
-- DELETE FROM "user";
SELECT * FROM "user";
INSERT INTO security_level (level,user_status) VALUES (1,'admin');
INSERT INTO security_level (level,user_status) VALUES (2,'user');
SELECT * FROM security_level;
INSERT INTO account (id,login,password,security_level_id,balance,email) VALUES (7,'log','pas',1,100.0,'a@r.ru');
INSERT INTO account (id,login,password,security_level_id,balance,email) VALUES (8,'log1','pas2',2,200.0,'f@r.ru');
INSERT INTO account (id,login,password,security_level_id,balance,email) VALUES (9,'log2','pas3',2,10.0,'w@r.ru');
INSERT INTO account (id,login,password,security_level_id,balance,email) VALUES (10,'log3','pas4',2,20.0,'j@r.ru');
INSERT INTO account (id,login,password,security_level_id,balance,email) VALUES (11,'log4','pas5',2,55.0,'l@r.ru');
SELECT * FROM account;
SELECT us.first_name,ac.security_level_id  FROM "user" us LEFT JOIN account ac ON us.id=ac.id;